name: web_scraper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.2.5
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.12.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
